### ISSUE TITLE
Can we add a component props to Chainable.Input

### ISSUE THREAD

**Issue by EQuimper** [samchamberland/react-native-chainable#1]
I think would be cool, if I can pass a component props to Chainable.Input, this way I can design it a a component and reuse it there.

```
<Chainable.Input ...otherProps component={MyInput} />
```

**Comment by samchamberland** [comment]
Good idea @EQuimper

If I get a chance I might implement this. In any case, PRs are always welcome.

Thanks for the suggestion 👍

**Comment by EQuimper** [comment]
Something like that

```js
if (this.props.component) {
      return React.createElement(this.props.component, {
        inputRef: this.ref,
        returnKeyType,
        ...this.props,
      });
    }

    return (
      <TextInput
        ref={this.ref}
        returnKeyType={returnKeyType}
        {...this.props}
      />
    );
```

**Comment by samchamberland** [comment]
I'm unlikely going to implement this. I'm personally fine with this limitation since we usually make use of `ref` directly when dealing with various components (e.g. pickers, different inputs, etc.). PR are always welcome but I'll close for now.
